# Generated by Django 2.2.10 on 2021-06-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210608_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastroModel',
            new_name='cadastro',
        ),
    ]
