# Generated by Django 2.2.10 on 2021-06-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20210608_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data',
            field=models.CharField(max_length=255, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='idade',
            field=models.CharField(max_length=255, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numero_da_dose',
            field=models.CharField(max_length=255, verbose_name='Numero da Dose'),
        ),
    ]
